language: scala

scala:
  - 2.9.2
  - 2.9.3
  - 2.10.4

jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS

script:
  # run for all environments
  - ./sbt ++$TRAVIS_SCALA_VERSION src/test/scala/unit

notifications:
  irc: "chat.freenode.net#finagle-zookeeper"