language: scala

scala:
  - 2.9.3

jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION finagle-zookeeper/test

notifications:
  irc: "chat.freenode.net#finagle-zookeeper"