language: scala

scala:
  - 2.10.3

jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

script:
  - "sbt ++$TRAVIS_SCALA_VERSION test-only com.twitter.finagle.exp.zookeeper.unit.*"

notifications:
  irc: "chat.freenode.net#finagle-zookeeper"